# Generated by Django 3.2.5 on 2021-07-24 11:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='profile_pics', verbose_name='Picture')),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('about', models.TextField(blank=True, max_length=50, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('Id_card_number', models.CharField(blank=True, max_length=50, null=True)),
                ('location', models.CharField(blank=True, max_length=50, null=True)),
                ('illness', models.CharField(blank=True, max_length=50, null=True)),
                ('drId', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PatientHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Prescription', models.TextField(blank=True, max_length=50, null=True)),
                ('nextVisit', models.DateTimeField(blank=True, null=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='profile_pics', verbose_name='Picture')),
                ('VisitDate', models.DateTimeField(auto_now_add=True)),
                ('Description', models.TextField(blank=True, max_length=50, null=True)),
                ('PatientId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patienthistory.patient')),
            ],
        ),
    ]
