# Generated by Django 3.2.5 on 2021-07-24 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patienthistory', '0002_auto_20210724_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='about',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='patienthistory',
            name='Description',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='patienthistory',
            name='Prescription',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
