# Generated by Django 3.2.5 on 2021-07-27 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patienthistory', '0003_auto_20210724_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patienthistory',
            name='nextVisit',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
