# Generated by Django 3.2.5 on 2021-07-27 13:05

from django.db import migrations, models
import patienthistory.models


class Migration(migrations.Migration):

    dependencies = [
        ('patienthistory', '0004_alter_patienthistory_nextvisit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=patienthistory.models.user_directory_path, verbose_name='Picture'),
        ),
        migrations.AlterField(
            model_name='patienthistory',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=patienthistory.models.user_hitory_path, verbose_name='Picture'),
        ),
    ]
